[base]
package = ocean
env_name = puffer_picopark
policy_name = PicoPark
rnn_name = Recurrent

[env]
num_envs = 512
view_width = 25
view_height = 14
height = 14
scroll_rate = 7
num_agents = 4

; [train]
; total_timesteps = 2_000_000_000
; gamma = 0.99
; learning_rate = 0.005
; ; minibatch_size = 16384
; minibatch_size = 32768
; ; bptt_horizon = 64             # Important for temporal reasoning
; ent_coef = 0.01               # CRITICAL - prevents policy collapse
; ; gae_lambda = 0.95
; ; clip_coef = 0.1
; checkpoint_interval = 500



[train]
total_timesteps = 1_000_000_000
; gamma = 0.99
; learning_rate = 0.0003
minibatch_size = 32768
; minibatch_size = 65536
ent_coef = 0.03
; max_grad_norm = 0.5
checkpoint_interval = 500


; 10_000_000_000